# Generated by Django 4.2.5 on 2023-10-03 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education_system', '0002_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonview',
            old_name='user',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='lessonview',
            name='status',
        ),
        migrations.AddField(
            model_name='lessonview',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='students',
            field=models.ManyToManyField(related_name='products_enrolled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
