# Generated by Django 4.2.5 on 2023-10-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_system', '0003_rename_user_lessonview_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonview',
            name='watched_time_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
