# Generated by Django 4.2.5 on 2023-10-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_system', '0004_alter_lessonview_watched_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='last_watched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
